DATA_ROOT: \hdd\lzq\PartA\biosignals_raw
MODEL_ROOT: \hdd\sdd\lzq\DLMM_new\model
LOGS_ROOT: \hdd\sdd\lzq\DLMM_new\model\logs

MODEL_NAME: experts_zd_voice_v11.t7
MODEL_NAME2: voice_bio_v11.t7

CHECKPOINT_NAME: experts_zd_face_v11.t7
CHECKPOINT_NAME2: experts_zd_voice_v11.t7
CHECKPOINT_NAME3: bio_v11.t7
CHECKPOINT_NAME4: bio_v11.t7

GPUID: "0"

EPOCH: 50
SUB_EPOCH: 10
BATCH_SIZE: 64
TCN_BATCH_SIZE: 1

FACE_OR_VOICE: voice
BIO_MODAL: bio

VGG_OR_RESNET: 1
EXTRACT_NUM: 512
HIDDEN_NUM: 64
CLASS_NUM: 9

TCN_OR_LSTM: 0
TCN_NUM: 3
TCN_HIDDEN_NUM: [128,128,64,32]

AU_INPUT_SIZE: [15,15]
AU_HIDDEN_SIZE: 32
AU_OUTPUT_SIZE: 32
PIC_SIZE: 224

TRAIN_RIO: 0.8
DATA_PATHS: [
  #2-138
  [\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\pain1,\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\label.csv,2],
  #139-244
  [\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\pain2,\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\label.csv,2],
  #255-312
  [\hdd\sdd\lzq\DLMM_new\dataset\2022.3.5\pain3,\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\label.csv,2],
  #313-352
  [\hdd\sdd\lzq\DLMM_new\dataset\2022.3.5\pain4,\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\label.csv,2],
  #353-509
  [\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\pain3,\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\label.csv,2],
  #510-582
  [\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\pain4,\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\label.csv,2],
  #583-720
  [\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\pain7,\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\label.csv,2],
  #721-843
  [\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\pain8,\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\label.csv,2],
  #844-1049
  [\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\pain5,\hdd\sdd\lzq\DLMM_new\dataset\2022.3.23\label.csv,2],
  ]
IS_POINT: True

LR: 0.001
WEIGHT_DELAY: 0.00001