DATA_ROOT: /hdd/lzq/PartA/biosignals_raw
MODEL_ROOT: /hdd/sda/lzq/DLMM_new/model
LOGS_ROOT: /hdd/sda/lzq/DLMM_new/model/logs
CLUSTER_ROOT: /hdd/sda/lzq/DLMM_new/model/cluster

MODEL_NAME: experts_face_v100_3f_new_
MODEL_NAME2: experts_face_voice_v11

CHECKPOINT_NAME: face_time_v100.t7
CHECKPOINT_NAME2: experts_face_v100_3f_kmeans0G.t7
CHECKPOINT_NAME3: experts_face_v100_5f_0G.t7
CHECKPOINT_NAME4: experts_face_voice_v11.t7

GPUID: "7"
SEED: 86

EPOCH: 100
SUB_EPOCH: 10
BATCH_SIZE: 64
TCN_BATCH_SIZE: 1
CLUSTER_EPOCH_SIZE_1: 1000
CLUSTER_EPOCH_SIZE_2: 20
CLUSTER_NUM: 3

MODAL: face

VGG_OR_RESNET: 1
EXTRACT_NUM: 3
HIDDEN_NUM: 64
CLASS_NUM: 9

TCN_OR_LSTM: 0
TCN_NUM: 3
TCN_HIDDEN_NUM: [128,128,64,32]

AU_INPUT_SIZE: [15,15]
AU_HIDDEN_SIZE: 32
AU_OUTPUT_SIZE: 32
PIC_SIZE: 224

TRAIN_RIO: 0.8
DATA_PATHS: [
  [/hdd/sda/lzq/DLMM_new/dataset/dataset,/hdd/sda/lzq/DLMM_new/dataset/dataset/label2.csv,4]
  #4 or 13
  # #2-138
  # [/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/pain1,/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/label.csv,2],
  # #139-244
  # [/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/pain2,/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/label.csv,2],
  # #255-312
  # [/hdd/sda/lzq/DLMM_new/dataset/2022.3.5/pain3,/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/label.csv,2],
  # #313-352
  # [/hdd/sda/lzq/DLMM_new/dataset/2022.3.5/pain4,/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/label.csv,2],
  # #353-509
  # [/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/pain3,/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/label.csv,2],
  # #510-582
  # [/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/pain4,/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/label.csv,2],
  # #583-720
  # [/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/pain7,/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/label.csv,2],
  # #721-843
  # [/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/pain8,/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/label.csv,2],
  # #844-1049
  # [/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/pain5,/hdd/sda/lzq/DLMM_new/dataset/2022.3.23/label.csv,2],
  ]
IS_POINT: True

LR: 0.001
WEIGHT_DELAY: 0.0001

SAMPLE_THRESHOLD: 16
SCORE_THRESHOLD: 0.2
