DATA_ROOT: '/hdd/lzq/PartA/biosignals_raw'
MODEL_ROOT: '/hdd/sdd/lzq/DLMM_new/model'
LOGS_ROOT: '/hdd/sdd/lzq/DLMM_new/model/logs'
MODEL_NAME: 'bio_tcn.t7'
CHECKPOINT_NAME: ['v4_face_rgb_res.t7','v4_voice_cry_tcn.t7']
GPUID: "1"

EPOCH: 50
SUB_EPOCH: 10
BATCH_SIZE: 1024
TCN_BATCH_SIZE: 128

FACE_OR_VOICE: 2

VGG_OR_RESNET: 1
EXTRACT_NUM: 512
HIDDEN_NUM: 64
CLASS_NUM: 3

TCN_OR_LSTM: 0
TCN_NUM: 3
TCN_HIDDEN_NUM: [32,16,16,1]

TRAIN_RIO: 0.9
DATA_PATHS: [
  ["/hdd/sdd/lzq/DLMM_new/dataset/2022.1.29/pain2","/hdd/sdd/lzq/DLMM_new/dataset/2022.1.29/pain2/label.csv",1],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.2.25/pain1","/hdd/sdd/lzq/DLMM_new/dataset/2022.2.25/pain1/label.csv",1],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.2.25/pain2","/hdd/sdd/lzq/DLMM_new/dataset/2022.2.25/pain2/label.csv",1],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.2.25/pain3","/hdd/sdd/lzq/DLMM_new/dataset/2022.2.25/pain3/label.csv",1],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.2.25/pain4","/hdd/sdd/lzq/DLMM_new/dataset/2022.2.25/pain4/label.csv",2],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.3.5/pain3","/hdd/sdd/lzq/DLMM_new/dataset/2022.3.5/label.csv",2],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.3.5/pain4","/hdd/sdd/lzq/DLMM_new/dataset/2022.3.5/label.csv",2],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.3.5/pain5","/hdd/sdd/lzq/DLMM_new/dataset/2022.3.5/label.csv",2],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/pain1","/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/label.csv",2],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/pain2","/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/label.csv",2],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/pain3","/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/label.csv",2],
  # ["/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/pain4","/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/label.csv",2],
  #["/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/pain5","/hdd/sdd/lzq/DLMM_new/dataset/2022.3.23/label.csv",2]
  ]
IS_POINT: True

LR: 0.0001
WEIGHT_DELAY: 0.00001